# Site Build Settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-sitemap, jekyll-seo-tag]
title:               'Davi A. Dal Fabbro'
