google-ID: 'UA-113032354-1'

menu:
- {name: 'Projects', url: 'projects.html'}
- {name: 'Writings', url: 'writings.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/ddfabbro'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/davidalfabbro/'}
- {icon: 'envelope', link: 'mailto:fabda01@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'
