# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-113032354-1'

menu:
- {name: 'Projects', url: 'projects.html'}
- {name: 'Writings', url: 'writings.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/ddfabbro'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/davidalfabbro/'}
- {icon: 'envelope', link: 'mailto:fabda01@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

#sharing_button_prompt: 'Feel free to share!'

#related_posts: 'You may also enjoy:'

#post_date_prefix: 'Written on'
